kind: secret
name: password_ccr
get:
  path: secrets
  name: password_ccr
---

kind: secret
name: id_feishu
get:
  path: secrets
  name: id_feishu
---

kind: secret
name: secret_feishu
get:
  path: secrets
  name: secret_feishu
---


kind: pipeline
type: docker
name: 发布


clone:
  disable: true


environment:
  NAME: nextcloud
  TAG: 0.0.$${DRONE_BUILD_NUMBER}


steps:
  - name: 代码
    image: ccr.ccs.tencentyun.com/dronestock/git
    pull: always

  - name: 发布
    image: ccr.ccs.tencentyun.com/dronestock/docker
    pull: always
    privileged: true
    volumes:
      - name: docker
        path: /var/lib/docker
    environment:
      PASSWORD_CCR:
        from_secret: password_ccr
    settings:
      repository: dockerat/$${NAME}
      tag: $${TAG}
      registry:
        hostname: ccr.ccs.tencentyun.com
        username: "160290688"
        password: $${PASSWORD_CCR}

  - name: 通知
    image: ccr.ccs.tencentyun.com/dronestock/feishu
    pull: always
    when:
      status:
        - success
        - failure
    settings:
      id:
        from_secret: id_feishu
      secret:
        from_secret: secret_feishu
      notfound:
        id: storezhang


volumes:
  - name: docker
    host:
      path: /var/lib/cache/docker
